language: node_js
os:
  - linux
  - osx
node_js:
  - node
  - 4
install:
  - npm install --ignore-scripts
  - npm run build
  - npm install
before_install:
  # install NPM 2
  - npm i -g npm@^2.0.0
after_success:
  # install travis-after-all script to enable running `semantic-release` after ALL build succeed
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  # run `semantic-release` exactly once after all builds pass
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  webhooks: http://webhook.hakatashi.com/travis
