language: node_js
node_js:
  - 'node'
  - '5'
install:
  - npm install --ignore-scripts
  - npm run build
  - npm install
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  webhooks: http://webhook.hakatashi.com/travis
